### ISSUE TITLE
Multiple crops per label sampling strategy

### ISSUE THREAD

**Issue by ThatOneGoat** [ThatOneGoat/sidewalk-cv-2021#22]
As per Jon's suggestion, we should add the ability to produce multiple crops of each label (perhaps 2 or 3). We will want to experiment with this a bit because our objects--like curb ramps--can be so many different sizes depending on the camera distance, viewpoint, etc.

An example of how the above proposal would look like:
![image](https://user-images.githubusercontent.com/37346427/142707583-28cd5732-aa1a-416f-aee9-c2db68c5b510.png)

**Comment by shokiami** [comment]
Here are some results:

188665_a.jpg
![188665_a](https://user-images.githubusercontent.com/43970567/143799414-f3291775-39be-4724-9111-4aea85f9d660.jpg)

188665_b.jpg
![188665_b](https://user-images.githubusercontent.com/43970567/143799420-40c92aca-5cc5-45ba-82c8-77a60f9beb0a.jpg)

188665_c.jpg
![188665_c](https://user-images.githubusercontent.com/43970567/143799423-789b5df9-6713-4d13-bb90-8d86afb00048.jpg)

**Comment by shokiami** [comment]
@ThatOneGoat

I added bounds-checking which significantly reduced the number of crops with black space. However, since there are some panoramas that contain black space (see below), there are still some crops that contain black space. This is also the reason why there are sometimes null crops that are pitch black. What do you think we should do about this?

![-cwI3Da84-kAoeTyk8rRVA](https://user-images.githubusercontent.com/43970567/143806825-43711fbd-23ec-439e-8272-d2524a034b3c.jpg)

**Comment by jonfroehlich** [comment]
Can't you just check to see if the crop is all black?

I would count the number of black pixels (or perhaps pixel values less than some threshold like 15). If ~50% of the image or more is black pixels, then discard.

**Comment by ThatOneGoat** [comment]
> Can't you just check to see if the crop is all black?
This would be a valid strategy if we wanted to just throw out crops. The problem is that this scaling difference between panoramas also affects the cropping of non-null crops, which we probably don't really want to throw out. 

We need to test this, but my intuition is that we can amend the issues with the smaller scaled panoramas by simply scaling them upwards to be the same dimensions as the larger panoramas (removing the black spaces on the right and bottom). That way we can just avoid black spaces in the crops in general and not have to throw out potentially useful data.
